"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Download, FileText, Sheet, Plus, Pencil } from "lucide-react";

import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { DataTable, type Column } from "@/components/ui/data-table";
import { cn } from "@/lib/utils";
import { staggerContainer, fadeUp } from "@/lib/motion";
import {
  reportTemplates,
  type ReportFormat,
  generatedReports,
  type GeneratedReport,
  scheduledReports,
  type ScheduledReport,
} from "@/lib/modules";

const TABS = [
  { key: "templates", label: "Templates" },
  { key: "generated", label: "Generated" },
  { key: "scheduled", label: "Scheduled" },
] as const;

const formatIcon: Record<ReportFormat, typeof FileText> = {
  PDF: FileText,
  Excel: Sheet,
};

function TemplatesGrid() {
  return (
    <motion.div
      variants={staggerContainer}
      initial="hidden"
      animate="show"
      className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"
    >
      {reportTemplates.map((t) => (
        <motion.div key={t.id} variants={fadeUp}>
          <Card className="glass card-seam h-full transition-colors hover:border-border-strong">
            <CardContent className="flex h-full flex-col gap-4 pt-5">
              <div className="flex size-10 items-center justify-center rounded-lg bg-accent-blue-soft text-accent-blue">
                <FileText className="size-5" />
              </div>
              <div className="flex flex-col gap-1">
                <span className="font-medium">{t.name}</span>
                <span className="text-sm text-muted-foreground">{t.description}</span>
              </div>
              <div className="mt-auto flex flex-wrap gap-2 border-t border-border pt-3">
                {t.formats.map((f) => {
                  const Icon = formatIcon[f];
                  return (
                    <Button key={f} size="sm" variant="secondary">
                      <Icon className="size-4" /> {f}
                    </Button>
                  );
                })}
              </div>
            </CardContent>
          </Card>
        </motion.div>
      ))}
    </motion.div>
  );
}

function GeneratedTable() {
  const columns: Column<GeneratedReport>[] = [
    { key: "name", header: "Name", render: (r) => <span className="font-medium">{r.name}</span> },
    {
      key: "format",
      header: "Format",
      render: (r) => (
        <Badge variant={r.format === "PDF" ? "red" : "green"}>{r.format}</Badge>
      ),
    },
    { key: "size", header: "Size", render: (r) => <span className="tnum text-muted-foreground">{r.size}</span> },
    { key: "by", header: "Generated by", render: (r) => <span className="text-muted-foreground">{r.by}</span> },
    { key: "at", header: "Time", align: "right", render: (r) => <span className="tnum text-muted">{r.at}</span> },
    {
      key: "actions",
      header: "",
      align: "right",
      render: () => (
        <Button size="sm" variant="ghost">
          <Download className="size-4" /> Download
        </Button>
      ),
    },
  ];

  return (
    <DataTable
      columns={columns}
      rows={generatedReports}
      getRowKey={(r) => r.id}
      empty="No reports generated yet."
    />
  );
}

function ScheduledTable() {
  const columns: Column<ScheduledReport>[] = [
    { key: "name", header: "Name", render: (r) => <span className="font-medium">{r.name}</span> },
    { key: "cadence", header: "Cadence", render: (r) => <span className="text-muted-foreground">{r.cadence}</span> },
    { key: "nextRun", header: "Next run", render: (r) => <span className="tnum">{r.nextRun}</span> },
    {
      key: "recipients",
      header: "Recipients",
      align: "right",
      render: (r) => <span className="tnum text-muted-foreground">{r.recipients}</span>,
    },
    {
      key: "actions",
      header: "",
      align: "right",
      render: () => (
        <Button size="sm" variant="ghost">
          <Pencil className="size-4" /> Edit
        </Button>
      ),
    },
  ];

  return (
    <div className="flex flex-col gap-3">
      <DataTable
        columns={columns}
        rows={scheduledReports}
        getRowKey={(r) => r.id}
        empty="No scheduled reports."
      />
      <p className="text-xs text-muted">
        Scheduled reports are emailed automatically to their recipient lists at the next run time.
      </p>
    </div>
  );
}

export default function ReportsPage() {
  const [tab, setTab] = useState<(typeof TABS)[number]["key"]>("templates");

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Reports"
        description="Generate, schedule and download operational reports."
        actions={
          <Button size="sm">
            <Plus className="size-4" /> New report
          </Button>
        }
      />

      <div className="flex items-center gap-1 border-b border-border">
        {TABS.map((t) => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            className={cn(
              "relative px-3 py-2.5 text-sm font-medium transition-colors",
              tab === t.key ? "text-foreground" : "text-muted hover:text-muted-foreground",
            )}
          >
            {t.label}
            {tab === t.key ? (
              <span className="absolute inset-x-2 -bottom-px h-0.5 rounded-full bg-accent-blue" />
            ) : null}
          </button>
        ))}
      </div>

      {tab === "templates" ? <TemplatesGrid /> : null}
      {tab === "generated" ? <GeneratedTable /> : null}
      {tab === "scheduled" ? <ScheduledTable /> : null}
    </div>
  );
}
